### ISSUE TITLE
PRIORITY:  The three panes should not be locked together when scrolling.  I.e., when I scroll down the words list, the map should stay where it is, visible however far down I scroll in the word or language columns.

### ISSUE THREAD

**Issue by PaulHeggarty** [sndcomp/website#71] opened 2015-02-09 09:29 UTC

**Comment by runjak** [comment] 2015-02-09 09:33
I think this is the same as #36.

**Comment by PaulHeggarty** [comment] 2015-02-09 09:56
Yes, but I really wanted to signal it as one of the top priorities, since there's no other good way of doing this in github.

**Comment by runjak** [comment] 2015-02-09 14:46
Right, I got that :)
Marking it as duplicate makes it easier for me to close both issues, once the problem is resolved.
An alternative would be to edit/comment an existing issue so that it turns up as recently changed.
Anyway I get a mail in both cases in this works just as well.

**Comment by PaulHeggarty** [comment] 2015-02-09 14:52
Hi

Ah, but you see this way you get the added satisfaction of being able to
kill two issues with one fix!  So all the more temptation to prioritise it.
;)

Paul

 

 

  _____

**Comment by runjak** [comment] 2015-02-09 15:21
Agreed - closing issues is rather satisfying (recently 50 issues where closes *yay!*)

**Closed** 2015-02-11 10:57 UTC
Labels: duplicate, enhancement
