### ISSUE TITLE
On the Mapundugun study site view, the study title does not appear in the gray box in the upper left corner next to the Max Planck Society emblem

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#87] opened 2015-03-18 09:59 UTC
Also, the drop down menue in this view is hidden behind the "show/hide languages" command

**Comment by runjak** [comment] 2015-03-19 09:38
Could reproduce by reducing the width of my browser window. That way this bug appears independently of the current study.

**Comment by runjak** [comment] 2015-03-20 09:15
I've developed a fix for this that 'should' work if the browser window is at least 1024px wide.
For widths below we would need to change the whole topMenu.
I think it is a safe enough assumption for now since the website is neither optimized for tablets nor phones, but assumes a wide enough screen to display all content.
This should be given in a desktop setting where resolutions below 1024x768 are expected to be rare.

**Closed** 2015-03-20 09:15 UTC
Labels: bug
