### ISSUE TITLE
The "Loading" window still appears only in English [the one that shows up when you enter the site]

### ISSUE THREAD

**Issue by LauraWae** [sndcomp/website#198] opened 2015-09-03 14:14 UTC

**Comment by runjak** [comment] 2015-09-03 19:04
Ah, thanks for reminding me. This is essentially a subtask of #173, if I'm not mistaken. I'll therefore close this issue as a duplicate and will close the referenced one once the problem is taken care of.

**Closed by runjak** 2015-09-03 19:04 UTC
Labels: duplicate
